[book]
title = "Rust Algorithm Club"
authors = ["Weihang Lo"]
description = "Learn algorithms and data structures with Rust"

[build]
build-dir = ".book"
create-missing = false

[output.html]
curly-quotes = true
no-section-label = true
mathjax-support = true # Disable it in order to add custom config.

[output.html.playpen]
editable = true
