[book]
title = "Rust Algorithm Club"
authors = ["Weihang Lo"]
description = "Learn algorithms and data structures with Rust"

[build]
build-dir = ".book"
create-missing = false

[output.html]
curly-quotes = true
no-section-label = true
mathjax-support = true
additional-js = ["theme/custom.js"]
git-repository-url = "https://github.com/weihanglo/rust-algorithm-club"

[output.html.playpen]
editable = true
